### ISSUE TITLE
Roadmap for v0.1.0

### ISSUE THREAD

**Issue by sundowndev** [dreamvo/gilfoyle#40]
List of features/changes we want to finish before releasing an official v0.1.0 version:

- [x] Web framework #14 
    - [x] OpenAPI specs
    - [x] ORM & schema implementation
    - [x] Validation
    - [x] JSON logging
- [x] Storage API #32 - **done**
    - [x] Filesystem
    - [x] S3 storage
    - [x] Google Cloud Storage
- [x] Upload tunnel (video only) - **done**
    - [x] REST routes #36 
    - [x] Async transcoding #85 
- [x] Streaming tunnel #85  **done**
    - [x] REST routes
    - [x] HLS playlists
- [x] Worker implementation #62 - **done**
- [x] Dashboard base implementation #46 - **done**
- [x] Dashboard UI framework implementation #73 - **done**

Please note that this list is changing.
